name: Make components public
run-name: Making components folder linket to punlic ğŸ› ï¸
on:
  push:
    branches: "dev"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: "Make link"
        run: |
          ls ./src/components
          mkdir ./public/ui
          ln -s ./src/components ./public/ui
          ls ./public/ui/components
